import admin from "firebase-admin";

type Timestamp = admin.firestore.Timestamp;
type TrophyGroup = {
  competitionId: string;
  competitionName: string;
  competitionLogo: string;
  competitionType: string; // e.g., "League", "Cup", "Continental"

  trophies: Trophy[];
};

type FirebaseTrophy = {
  id?: string;               // Auto-generated by Firestore
  teamId: string;
  teamName: string;
  teamLogo: string;

  competitionId: string;
  competitionName: string;
  competitionLogo: string;
  competitionType: string; // e.g., "League", "Cup", "Continental"

  season: string;           // "2024/25"
  game: string;             // "FM24", "FM25", etc.
  countryCode: string;     // Optional, if needed for filtering or display

  dateWon?: string;         // ISO string, optional
  createdAt: string | Timestamp; // Mixed formats in data
  updatedAt?: Timestamp;
};

type TrophyInput = {
  teamId: string;
  competitionId: string;
  dateWon: string;
  countryCode: string;
  game: string;             // "FM24", "FM25", etc.
};

export type { FirebaseTrophy, TrophyInput, TrophyGroup };