type Trophy = {
  id: string;               // Auto-generated by Firestore
  teamId: string;
  teamName: string;
  teamLogo: string;

  competitionId: string;
  competitionName: string;
  competitionLogo: string;
  competitionType: string; // e.g., "League", "Cup", "Continental"

  season: string;           // "2024/25"
  createdAt: string;        // ISO string
};

type TrophyInput = {
  teamId: string;
  competitionId: string;
  dateWon: string;
  countryCode: string;
};

export type { Trophy, TrophyInput };